version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5235:80"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: AsmvDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=AsmvDatabase;Username=postgres;Password=postgres"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: AsmvDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
